### ISSUE TITLE
Gifs not Giffing during setup

### ISSUE THREAD

**Issue by Ormatist** [The-Iceburg/TotemsPlus#48]
During the totem setup if an image is submitted that is a gif this gif doesn't play when this texture is cycled to this is due to the resizing of the image earlier in the code (#21)

**Comment by Dockuin** [comment]
After conducting a bit more research on the matter, there is a higher likelihood of this working and I will proceed to follow up with the situation.
This might become redundant, however, as we are likely to be changing GUI implementation.
Updates to come.
