### ISSUE TITLE
Custom Advancements

### ISSUE THREAD

**Issue by Ormatist** [The-Iceburg/TotemsPlus#8]
Add a new (toggleable) feature (probably in a new script at this point) which allows a custom achievement tab to be generated in which the user can be granted achievements for collecting the custom totems. This could also link to their rarities. And additional achievements could be collecting all custom totems

**Comment by Dockuin** [comment]
Change previous code to have counter start at one so we can force a mandatory totems plus logo as a totem - for usage with the "Collect them all!" advancement

**Comment by Ormatist** [comment]
Planning has begun for this issue, after layout has been finalised implementation will begin

**Comment by Ormatist** [comment]
This issue is going to be a big one but we do want to fit it in before beta v1.0.0 It will probably be the last big feature we implement before bugfixes and release bringing us to around 0.9.5+
